import "server-only";
import type { SiteContent } from "@/lib/content-source";
// Generated by scripts/bundle-content.ts (runs before dev, build, test and typecheck).
import bundled from "@/lib/generated/content.json";

/**
 * Curated content from `content/sites/**`. Production serves the build-time
 * bundle, since Cloudflare Workers have no project filesystem; `next dev`
 * reads the markdown directly so editors see changes without a rebuild.
 */
const fromDisk = () => process.env.NODE_ENV === "development";

const contentDir = async () => (await import("node:path")).join(process.cwd(), "content/sites");

/** Curated markdown for one site, in canonical section order. Missing files are skipped. */
export async function readSiteContent(slug: string): Promise<SiteContent> {
  if (fromDisk()) {
    const { readSiteContentFromDisk } = await import("@/lib/content-source");
    return readSiteContentFromDisk(await contentDir(), slug);
  }
  return (bundled as Record<string, SiteContent>)[slug] ?? { vi: [], en: [] };
}

/** Slugs that have curated content. */
export async function listContentSlugs(): Promise<string[]> {
  if (fromDisk()) {
    const { listSlugsOnDisk } = await import("@/lib/content-source");
    return listSlugsOnDisk(await contentDir());
  }
  return Object.keys(bundled);
}
